# Tugas Pertemuan 3 Data Mining

### Aulia Diaz Gustiavani
### A11.2022.14446
### A11.4509

# Data Preprocessing Template

### Import library yang digunakan

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Import Dataset

In [2]:
dataset = pd.read_csv('Data2.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['Tokyo' 32.0 67000.0]
 ['New York' 45.0 82000.0]
 ['Berlin' nan 51000.0]
 ['Sydney' 36.0 62000.0]
 ['Paris' 41.0 70000.0]
 ['Tokyo' 33.0 58000.0]
 ['Berlin' 39.0 74000.0]
 ['New York' 29.0 nan]]


In [4]:
print(y)

['No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No']


### Menghilangkan Missing Value (nan)

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[['Tokyo' 32.0 67000.0]
 ['New York' 45.0 82000.0]
 ['Berlin' 36.42857142857143 51000.0]
 ['Sydney' 36.0 62000.0]
 ['Paris' 41.0 70000.0]
 ['Tokyo' 33.0 58000.0]
 ['Berlin' 39.0 74000.0]
 ['New York' 29.0 66285.71428571429]]


### Encoding Data Kategori (Atribut)

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[0.0 0.0 0.0 0.0 1.0 32.0 67000.0]
 [0.0 1.0 0.0 0.0 0.0 45.0 82000.0]
 [1.0 0.0 0.0 0.0 0.0 36.42857142857143 51000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 62000.0]
 [0.0 0.0 1.0 0.0 0.0 41.0 70000.0]
 [0.0 0.0 0.0 0.0 1.0 33.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 39.0 74000.0]
 [0.0 1.0 0.0 0.0 0.0 29.0 66285.71428571429]]


### Encoding Data Kategori (Class / Label)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 1 0 1 1 0]


### Membagi Dataset ke dalam training set dan test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X_train)

[[0.0 1.0 0.0 0.0 0.0 45.0 82000.0]
 [1.0 0.0 0.0 0.0 0.0 39.0 74000.0]
 [0.0 0.0 0.0 0.0 1.0 32.0 67000.0]
 [0.0 0.0 1.0 0.0 0.0 41.0 70000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 62000.0]
 [0.0 0.0 0.0 0.0 1.0 33.0 58000.0]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 0.0 0.0 29.0 66285.71428571429]
 [1.0 0.0 0.0 0.0 0.0 36.42857142857143 51000.0]]


In [14]:
print(y_train)

[1 1 0 0 1 1]


In [15]:
print(y_test)

[0 0]


### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [17]:
print(X_train)

[[0.0 1.0 0.0 -0.4472135954999579 -0.7071067811865475 1.6174721686063775
  1.6793313066801396]
 [1.0 0.0 0.0 -0.4472135954999579 -0.7071067811865475 0.29408584883752364
  0.6589781076846121]
 [0.0 0.0 0.0 -0.4472135954999579 1.4142135623730951 -1.2498648575594726
  -0.23383094143647443]
 [0.0 0.0 1.0 -0.4472135954999579 -0.7071067811865475 0.7352146220938083
  0.14880150818684837]
 [0.0 0.0 0.0 2.23606797749979 -0.7071067811865475 -0.36760731104690336
  -0.8715516908086791]
 [0.0 0.0 0.0 -0.4472135954999579 1.4142135623730951 -1.0293004709313303
  -1.3817282903064427]]


In [18]:
print(X_test)

[[0.0 1.0 0.0 -0.4472135954999579 -0.7071067811865475 -1.9115580174438997
  -0.32493390563250313]
 [1.0 0.0 0.0 -0.4472135954999579 -0.7071067811865475
  -0.27307971677769904 -2.2745373394275292]]
